[package]
name = "thesis-full-sweep-host"
version = "0.1.0"
edition = "2021"
default-run = "thesis-full-sweep-host"

[dependencies]
thesis-full-sweep-methods = { path = "../methods" }
risc0-zkvm = { path = "/root/arguzz/workspace/risc0-modified/risc0/zkvm" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.0", features = ["derive", "env"] }
fuzzer_utils = { path = "/root/arguzz/workspace/risc0-modified/fuzzer_utils" }

[features]
default = ["prove"]
prove = ["risc0-zkvm/prove", "risc0-zkvm/witgen_debug"]
